version: '3.6'

services:
  app:
    build:  ./
    ports:
      - 8080:8080

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8081:8080
    volumes:
      - ./api/swagger-spec:/spec
    environment:
      SWAGGER_JSON: /spec/openapi.yaml