name: PROD - Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Update the dropplet
        uses: appleboy/scp-action@master
        env:
          HOST: ${{secrets.PRO_SERVER_HOST}}
          USERNAME: ${{secrets.PRO_SERVER_USERNAME}}
          PORT: ${{secrets.PRO_SERVER_PORT}}
          KEY: ${{secrets.PRO_SERVER_PRIVATE_KEY}}
        with:
          rm: true
          source: "."
          target: "/opt/app"
      - name: Build the container and run it.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRO_SERVER_HOST }}
          username: ${{ secrets.PRO_SERVER_USERNAME }}
          key: ${{ secrets.PRO_SERVER_PRIVATE_KEY }}
          passphrase: ${{ secrets.PRO_SERVER_PASSPHRASE }}
          port: ${{ secrets.PRO_SERVER_PORT }}
          script: |
            chmod +x /opt/app/run.sh
            /opt/app/run.sh
          debug: true